#pragma once

#define GAMEPLATFORM_DUMMY 0
#define GAMEPLATFORM_STEAM 1
#define GAMEPLATFORM_PLAYSTATION 2
#define GAMEPLATFORM_NSWITCH 3
#define GAMEPLATFORM_XBOXONE 4

#define GAMEPLATFORM GAMEPLATFORM_DUMMY