#pragma once

#include <XeSDK.h>
#include <XeGame/IAtom.h>
#include <XeGame/IEntity.h>
#include <XeGame/IEntityManager.h>
#include <XeGame/ITextureManager.h>
#include <XeGame/IGameTilemap2d.h>
#include <XeGame/IGameSoundManager.h>
#include <XeGame/IGameSoundBgmEntity.h>
#include <XeGame/IGameSoundSfxEntity.h>
#include <XeGame/XeGameAnimationDef.h>
#include <XeGame/XeGameEaseFunctions.h>
#include <XeGame/XeGameDrawing2d.h>
#include <XeGame/XeGameTilemap2d.h>
#include <XeGame/XeGameTextureManager.h>
#include <XeGame/XeGameSoundManager.h>
#include <XeGame/XeGameImGuiHandler.h>
#include <XeGame/XeGameToolsTextureDebugger.h>
#include <XeGame/XeGameToolsTilemapDebugger.h>
#include <XeGame/XeGameToolsFilePicker.h>
#include <XeGame/XeGameTiledDocument.h>