#pragma once

#include <XeSDK/IDriversRenderingDriver.h>
#include <XeSDK/IDriversSoundDriver.h>
#include <XeSDK/IDriversGamepadDriver.h>
#include <XeSDK/ICollection.h>
#include <XeSDK/IComparable.h>
#include <XeSDK/IDelegate.h>
#include <XeSDK/IFrameView.h>
#include <XeSDK/ICoreView.h>
#include <XeSDK/IDictionary.h>
#include <XeSDK/IEnumerable.h>
#include <XeSDK/IGraphicsContext.h>
#include <XeSDK/IGraphicsDrawing2d.h>
#include <XeSDK/IGraphicsTilemap.h>
#include <XeSDK/IIOFileStream.h>
#include <XeSDK/IIOMemoryStream.h>
#include <XeSDK/INetSocket.h>
#include <XeSDK/ISoundAudioEffect.h>
#include <XeSDK/ISoundSoundFormatFactory.h>

#include <XeSDK/XeCollections.h>
#include <XeSDK/XeCollectionsArray.h>
#include <XeSDK/XeCollectionsStaticArray.h>
#include <XeSDK/XeCore.h>
#include <XeSDK/XeCoreFrameView.h>
#include <XeSDK/XeCryptoCrc32.h>
#include <XeSDK/XeCryptoCrc64.h>
#include <XeSDK/XeDrivers.h>
#include <XeSDK/XeEvent.h>
#include <XeSDK/XeGraphics.h>
#include <XeSDK/XeGraphicsImaging.h>
#include <XeSDK/XeGraphicsImagingPng.h>
#include <XeSDK/XeGraphicsFont.h>
#include <XeSDK/XeGraphicsFontUV.h>
#include <XeSDK/XeIO.h>
#include <XeSDK/XeIODevices.h>
#include <XeSDK/XeIOGamepad.h>
#include <XeSDK/XeIOPointer.h>
#include <XeSDK/XeLogger.h>
#include <XeSDK/XeMath.h>
#include <XeSDK/XeMathRandom.h>
#include <XeSDK/XeMathRectangle.h>
#include <XeSDK/XeMathVector2.h>
#include <XeSDK/XeMathVector3.h>
#include <XeSDK/XeMathVector4.h>
#include <XeSDK/XeMathMatrix.h>
#include <XeSDK/XeMemory.h>
#include <XeSDK/XeObjPtr.h>
#include <XeSDK/XeSound.h>
#include <XeSDK/XeSoundPlayable.h>
#include <XeSDK/XeSoundSoundFormatFactory.h>
#include <XeSDK/XeSoundOggSoundFormatFactory.h>
#include <XeSDK/XeSoundWavSoundFormatFactory.h>
#include <XeSDK/XeStorage.h>
#include <XeSDK/XeStorageContainerXefs.h>
#include <XeSDK/XeStoragePath.h>
#include <XeSDK/XeString.h>
#include <XeSDK/XeStringSpan.h>
#include <XeSDK/XeTimer.h>

#include <XeSDK/XeGameComponentPosition2d.h>
#include <XeSDK/XeGameComponentTexture2d.h>
#include <XeSDK/XeGameComponentSprite.h>